oracle_version: "dev/binning-normalisation"
oracle_arguments:
  data_transformation:
    feature_config_list:
    - is_target: True
      transformation:
        name: log-return
      normalization: standard
      name: close
    exchange_name: "NYSE"
    features_resample_minutes: 15
    features_start_market_minute: 60
    prediction_frequency_ndays: 1
    prediction_market_minute: 60
    target_delta_ndays: 2
    target_market_minute: 60

  train_path: '/datadrive/train'
  tensorboard_log_path: '/datadrive/tensorboard'
  covariance_method: Ledoit
  covariance_ndays: 100
  model_save_path: '/datadrive/model'
  d_type: float32
  tf_type: 32
  random_seed: 0
  predict_single_shares: True
  n_epochs: 200
  n_retrain_epochs: 5
  n_training_samples: 15800
  learning_rate: 0.001
  batch_size: 200
  cost_type: bayes
  n_train_passes: 1
  n_eval_passes: 8
  resume_training: True
  n_series: 1
  nassets: 400
  n_features_per_series: 271
  n_forecasts: 1
  n_classification_bins: 12
  classify_per_series: True
  normalise_per_series: True
  layer_heights:
  - 400
  - 400
  - 400
  - 400

  layer_widths:
  - 1
  - 1
  - 1
  - 1

  layer_types:
  - full
  - full
  - full
  - full

  activation_functions:
  - relu
  - relu
  - relu
  - linear

  INITIAL_ALPHA: 0.05
  INITIAL_WEIGHT_UNCERTAINTY: 0.02
  INITIAL_BIAS_UNCERTAINTY: 0.02
  INITIAL_WEIGHT_DISPLACEMENT: 0.1
  INITIAL_BIAS_DISPLACEMENT: 0.1
  USE_PERFECT_NOISE: False
  double_gaussian_weights_prior: True
  wide_prior_std: 1.0
  narrow_prior_std: 0.001
  spike_slab_weighting: 0.25
  n_training_samples_benchmark: 1000
  n_correlated_series: 1
  use_historical_covariance: True
